### ISSUE TITLE
App crashes on device without gapps when granting location access

### ISSUE THREAD

**Issue by rradar** [dfloureiro/open-ipma#5]
Hi @dfloureiro 

finally I got your app on my device (Lineage OS 15.1 = Android 8.1 without google services).

The app starts when I do not grant location access and works.

When I grant the app to access my device location the app crashes on start and 'keeps stopping'.

When I disable the location access again the app behaves normal and starts without errors.

Anything I can provide to help debugging?

**Comment by dfloureiro** [comment]
Hi! Thank you for reporting it, the report was catched by crashlytics so I have the logs, that should be enough. I'll fix it asap, and update the app 👍

**Comment by dfloureiro** [comment]
solved on the next release
